### ISSUE TITLE
prime editing > introduce variation > enter ClinVar ID > 'NoneType' object has no attribute lower

### ISSUE THREAD

**Issue by emmazchen** [emmazchen/crispr-gpt-tracker#1]
<img width="1173" alt="Screenshot 2024-05-17 at 2 42 04 PM" src="https://github.com/emmazchen/crispr-gpt-testing/assets/114841242/92c54b99-85ff-449e-a5e9-efde9bb9c7e8">

**Comment by emmazchen** [comment]
With another input
<img width="949" alt="Screenshot 2024-05-20 at 10 01 07 AM" src="https://github.com/emmazchen/crispr-gpt-tracker/assets/114841242/b96b96b7-8fab-4a20-80b0-8e1d8adbb76a">

**Comment by zhanhugo** [comment]
fixed
