### ISSUE TITLE
Off-target step not defined in Auto-mode?

### ISSUE THREAD

**Issue by congle25** [emmazchen/crispr-gpt-tracker#7]
I tried to enter CRISPRitz in Auto-mode, but got an error, it would be great for Hugo @zhanhugo and @Kaffaljidhmah2 Kaixuan to decide if it's simple to enable user to quickly enter this off-target step. Ideally we could have user directly enter the CRISPRitz using similar prompt. But we could also save this issue for later.

Error is "**module 'crisprgpt.off_target' has no attribute 'StateStep1' Let's try again.**"

Please see image below:
<img width="834" alt="image" src="https://github.com/emmazchen/crispr-gpt-tracker/assets/7317829/bd54dc84-c4cc-4018-bdb6-6f41c3e30011">

**Comment by zhanhugo** [comment]
fixed
